language: python

python:
  - "3.6.1"

dist: trusty

env:
  global:
    - BUILD_ON_TRAVIS=true

install:
  - pip3 install -r requirements.txt

script:
  - python manage.py migrate -v 3
  - python manage.py test -v 3