language: python

python:
  - "3.6.1"

dist: trusty

env:
  global:
    - BUILD_ON_TRAVIS=true

install:
  - pip3 install -r requirements.txt

script:
  - python3 manage.py migrate -v 3
  - python3 manage.py loaddata mail_template_entity
  - python3 manage.py test -v 3