# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-17 19:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailtor', '0002_auto_20171216_1948'),
    ]

    operations = [
        migrations.AddField(
            model_name='mail',
            name='mode_html',
            field=models.BooleanField(default=False),
        ),
    ]
