# Generated by Django 2.0 on 2017-12-18 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailtor', '0003_mail_mode_html'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='attachment',
            field=models.FileField(default=None, upload_to='attachment'),
            preserve_default=False,
        ),
    ]
