# Generated by Django 2.0 on 2017-12-19 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailtor', '0004_auto_20171218_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attachment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='mailtemplateentities',
            name='label',
            field=models.CharField(default=None, max_length=10),
            preserve_default=False,
        ),
    ]
