# Generated by Django 2.0 on 2017-12-19 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailtor', '0005_auto_20171219_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailtemplateentities',
            name='label',
            field=models.CharField(max_length=25),
        ),
    ]
