# Generated by Django 2.0 on 2017-12-19 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailtor', '0006_auto_20171219_1303'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailtemplateentities',
            name='label',
        ),
    ]
