# Generated by Django 2.0 on 2017-12-19 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailtor', '0007_remove_mailtemplateentities_label'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MailTemplateEntities',
            new_name='MailTemplateEntity',
        ),
        migrations.AlterModelOptions(
            name='mailtemplateentity',
            options={'verbose_name': 'MailTemplateEntity', 'verbose_name_plural': 'MailTemplateEntitys'},
        ),
    ]
