# Generated by Django 2.0 on 2017-12-19 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailtor', '0008_auto_20171219_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailtemplateentity',
            name='kind',
            field=models.IntegerField(choices=[(1, 'Direct'), (2, 'Image'), (3, 'Date'), (4, 'Time'), (5, 'Datetime'), (6, 'Link')], default=1),
        ),
    ]
