# Generated by Django 2.0 on 2017-12-22 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailtor', '0010_auto_20171221_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='mail',
            name='detail_error',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='mail',
            name='error_code',
            field=models.IntegerField(blank=True, choices=[(1, 'Error en datos de reemplazos'), (2, 'Error en valores de reemplazos'), (3, 'Error servicio de envió de email')], default=1, null=True),
        ),
    ]
