# Generated by Django 2.0 on 2017-12-22 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailtor', '0011_auto_20171222_1443'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mail',
            old_name='detail_error',
            new_name='error_detail',
        ),
    ]
