# Generated by Django 2.0 on 2017-12-22 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailtor', '0013_auto_20171222_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mail',
            name='error_code',
            field=models.IntegerField(blank=True, choices=[(1, 'Error en datos de reemplazos'), (2, 'Error en valores de reemplazos'), (3, 'Error servicio de envió de email'), (4, 'Error email sin texto')], default=None, null=True),
        ),
    ]
