# Generated by Django 2.0 on 2017-12-26 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailtor', '0016_auto_20171222_2002'),
    ]

    operations = [
        migrations.AddField(
            model_name='mail',
            name='opened_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
